@startuml

!theme vibrant

database Data {
}

[Front-end]
buy - [Checkout] : 8081/8444
pay - [Payment] : 8082/8445
getJwt - [Users] : 8080/8443

[Front-end] --> getJwt : Credentials (1)
Users <--> Data :  Credentials (2)
getJwt --> [Front-end] : JWT (3)
[Front-end] --> buy :  JWT (4)
buy --> pay :  JWT (5)

@enduml