@startuml

!theme vibrant

database Data {
}

[Front-end]
sum - [BFF] : 8081/8445
getSum - [Backend] : 8082/8444
getjwt - [Users] : 8080/8443

[Front-end] --> getjwt : (1)
Users --> Data : (2)
[Front-end] --> sum : (3)
sum --> getSum : (4)

@enduml