@startuml

!theme vibrant

database Data {
}

[Front-end]
sum - [First] : 8081/8444
getSum - [Second] : 8082/8445
jwt - [Users] : 8080/8443

[Front-end] --> jwt : (1)
Users --> Data : (2)
[Front-end] --> sum : (3)
sum --> getSum : (4)

@enduml